### ISSUE TITLE
Detailed Itinerary Instructions

### ISSUE THREAD

**Issue by Firelods** [Firelods/Middleware-project#4]
# Create a section where users can see turn-by-turn instructions for their route.

## Tasks:

- [ ] Display step-by-step instructions such as “Turn right in 50 meters”.
- [ ] Include estimated travel time and distance.
- [ ] Add the ability to refresh instructions when the user changes the route.
- [ ] _Integrate with the map to highlight specific parts of the route when a step is clicked._
